### ISSUE TITLE
HA controls bulbs OK but does not recognize their color etc. once set. 11A19060WRGBWH1; integration v3.0.4

### ISSUE THREAD

**Issue by pem884** [jdeath/Hubspace-Homeassistant#101] opened 2024-08-10 01:42 UTC
I noticed very recently (in the past week?) that my two Hubspace bulbs `11A19060WRGBWH1`:
I can change color and brightness via HA and Hubspace app; it works fine.
After I change color and/or brightness from HA, HA changes the appearance of the light to something other than what it actually is. HA does seem to "understand" whether the light is on or off, but perhaps not color/brightness(/other?) attributes.

So we have all the information in one place, it was mentioned in the HA forum that "There was an issue that brightness was not initialized yet, so this is probably similar."

[_dump_hs_devices.json](https://github.com/user-attachments/files/16568084/_dump_hs_devices.json)
[_dump_hs_raw.json](https://github.com/user-attachments/files/16568086/_dump_hs_raw.json)

(edit: adding the output of TestHubspace.py in case it's more convenient) 
[TestHubspaceOutput.json](https://github.com/user-attachments/files/16570303/TestHubspaceOutput.json)

I'm happy to help with more dumps, testing, etc.

**Comment by Expl0dingBanana** [comment] 2024-08-10 19:24
I have confirmed this is an issue. I will let you know when a beta release is available with the fix

**Comment by Expl0dingBanana** [comment] 2024-08-11 00:20
The root cause was how I was handling color-mode / effects. There is a fix in the branch but I am going to ensure all sequences get added, not just "custom" ones. I want to fix that issue prior to creating PR / dev release with the fix.

**Comment by Expl0dingBanana** [comment] 2024-08-11 01:48
I believe this has been fixed with #102  . Please review the testing instructions within that PR and post any comments within that PR.

**Comment by Expl0dingBanana** [comment] 2024-08-12 10:39
Issue resolved in #102 and was merged to main.

**Closed by Expl0dingBanana** 2024-08-12 10:39 UTC
